### ISSUE TITLE
Submit a new Good Practice - Remove maximum character limit from description

### ISSUE THREAD

**Issue by kopitek8** [idmc-labs/idmc-website-components#97]
## Client Requirement

Remove the character limit for the body of text, or double the current limit if it has to remain.

## Where Are They?

- Submit a Good Practice modal

## To Do

- Remove the max character limit of 10,000 in both English and French textfields
- Remove the logic of checking for max character (as shown in screenshot below)

![Image](https://github.com/idmc-labs/idmc-website-components/assets/25280806/348a08ee-22ae-49dc-a36c-7954ce9b07eb)

**Comment by bramverweij** [comment]
Tested in Staging, the Character limit has been removed for the following: 
- Description of the project [en]:
- Description of the project [fr]:
- Media and resource links (Links to any relevant reports, evaluations or other documents) [en]:
- Media and resource links (Links to any relevant reports, evaluations or other documents) [fr]:
